name: riverpod_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod: ^3.0.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  go_router: ^16.3.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/OTF/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/OTF/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/OTF/Satoshi-Regular.otf
          weight: 500
        - asset: assets/fonts/OTF/Satoshi-Black.otf
          weight: 600
        - asset: assets/fonts/OTF/Satoshi-Bold.otf
          weight: 700
